steps:
- label: ':docker: Build'
  plugins:
  - docker-compose#v2.6.0:
      build: test-cpu

- wait

- label: ':docker: Test Keras MNIST'
  command: eval "$(cat /mpirun_command) python /horovod/examples/keras_mnist_advanced.py"
  plugins:
  - docker-compose#v2.6.0:
      run: test-cpu

- label: ':docker: Test PyTorch MNIST'
  command: eval "$(cat /mpirun_command) python /horovod/examples/pytorch_mnist.py"
  plugins:
  - docker-compose#v2.6.0:
      run: test-cpu

- wait

- label: ':hammer: nvidia-smi'
  plugins:
  - docker-compose#v2.6.0:
      run: nvidia-smi
